### ISSUE TITLE
the import of include-media

### ISSUE THREAD

**Issue by jajourda** [fredericpfisterer/jekyll-mix#1]
how is the tilde ~ employed as a means of referencing the include-media folder in the node_modules directory?

![image](https://user-images.githubusercontent.com/1839603/38258386-53d6aaca-3730-11e8-84cc-87f3ccf68047.png)
btw, this is more  a new user question label, but i don't think i can apply a label to your repository issues.

**Comment by jajourda** [comment]
also, how do you use an external javascript file? do you require it in app.js?

**Comment by fredericpfisterer** [comment]
This how [Webpack / Sass Loader](https://github.com/webpack-contrib/sass-loader#imports) works :-)

And this [one](https://webpack.js.org/guides/code-splitting/) is for your second question !
